# Generated by Django 5.2.10 on 2026-01-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('DOCUMENT_CREATED', 'Document created'), ('DOCUMENT_SUBMITTED', 'Document submitted'), ('DOCUMENT_APPROVED', 'Document approved'), ('DOCUMENT_REJECTED', 'Document rejected')], max_length=50),
        ),
    ]
