# Generated by Django 5.2.10 on 2026-01-22 19:31

from django.db import migrations

ACTION_MAP = {
    "Document CREATED": "DOCUMENT_CREATED",
    "Document SUBMITTED": "DOCUMENT_SUBMITTED",
    "Document APPROVED": "DOCUMENT_APPROVED",
    "Document REJECTED": "DOCUMENT_REJECTED",
}


def forwards(apps, schema_editor):
    AuditLog = apps.get_model("workflow", "AuditLog")

    for old, new in ACTION_MAP.items():
        AuditLog.objects.filter(action=old).update(action=new)


def backwards(apps, schema_editor):
    AuditLog = apps.get_model("workflow", "AuditLog")

    reverse_map = {v: k for k, v in ACTION_MAP.items()}
    for new, old in reverse_map.items():
        AuditLog.objects.filter(action=new).update(action=old)


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
