# Generated by Django 5.2.10 on 2026-02-08 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_normalize_audit_actions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.UniqueConstraint(fields=('document',), name='unique_approval_per_document'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['APPROVED', 'REJECTED'])), name='approvalstep_terminal_status_only'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED'])), name='document_status_valid'),
        ),
    ]
